http:
  host: 'localhost'
  port: 4018
  contextPath: accounting

description: 'Accounting Service'

rabbit:
  protocol: amqp
  hostname: localhost
  username: guest
  password: guest
  port: 5672
  heartbeat: 1
  queue: 'localhost'
  retry:
    # forever: true
    retries: 5
    factor: 1
    minTimeout: 3000
    maxTimeout: 20000
mongoose:
  uri: mongodb://localhost:27017/accounting
  
redis:
  host: localhost
  port: 6379
  password: null
  db: 1

throttler:
  - name: short
    ttl: 1000
    limit: 3
  - name: medium
    ttl: 10000
    limit: 20
  - name: long
    ttl: 60000
    limit: 100

accountingConsumer:
  paymentCheckoutOrder:
    queue: payment_checkout_order
    prefetchCount: 2
    queueType: quorum
    exchange: eca
    routingKey: eca.payment_checkout_order
    deadLetterExchange: eca
    deadLetterRoutingKey: eca.payment_checkout_order.errors
    retryTime: 3000
    maxRetries: 1

accountingProducer:
  orderConfirmedPayment:
    exchange: eca
    routingKey: eca.order_confirmed_payment
    
stripe:
  clientId: pk_test_51LNC3lCusYszZLeuaMpqfLXOxDpL7Aonfe9waLgjrB1dU6TsnmE3f3CTxB2KVueo6r5YdZx6qNdRxEzyHHQ7k5rd00TYTKuq9X
  clientSecretKey: sk_test_51LNC3lCusYszZLeuiI5tii8ydiTB5GkHLt9I2e1MAgrSOIncsNKVEuJD4rtTQt87FuypROmPGNCF9yyh4k6qSciS0070uMMnzZ