http:
  host: 'localhost'
  port: 4099
  contextPath: basket

description: 'Basket Service'

rabbit:
  protocol: amqp
  hostname: localhost
  username: guest
  password: guest
  port: 5672
  heartbeat: 1
  queue: 'localhost'
  retry:
    # forever: true
    retries: 5
    factor: 1
    minTimeout: 3000
    maxTimeout: 20000
mongoose:
  username: guest
  password: guest
  uri: null
  host: localhost
  port: 27017
  database: microservices

redis:
  url: localhost
  password: null
  socket:
    port: 6379
    connectTimeout: 60000
  database: 1

throttler:
  - name: short
    ttl: 1000
    limit: 3
  - name: medium
    ttl: 10000
    limit: 20
  - name: long
    ttl: 60000
    limit: 100

basketProducer:
  orderCreated:
    exchange: eca
    routingKey: eca.order_created

basketConsume:
  cartDeleted:
    queue: cart_deleted
    queueType: quorum
    exchange: eca
    routingKey: eca.cart_deleted
    deadLetterExchange: eca
    deadLetterRoutingKey: eca.cart_deleted
    retryTime: 3000
    maxRetries: 1
