http:
  host: 'localhost'
  port: 4017
  contextPath: catalog

description: 'Catalog Service'

rabbit:
  protocol: amqp
  hostname: localhost
  username: guest
  password: guest
  port: 5672
  heartbeat: 1
  queue: 'localhost'
  retry:
    # forever: true
    retries: 5
    factor: 1
    minTimeout: 3000
    maxTimeout: 20000
mongoose:
  uri: mongodb://localhost:27017/catalog
redis:
  url: localhost
  password: null
  socket:
    port: 6379
    connectTimeout: 60000
  database: 1

throttler:
  - name: short
    ttl: 1000
    limit: 3
  - name: medium
    ttl: 10000
    limit: 20
  - name: long
    ttl: 60000
    limit: 100

catalogConsumer:
  productValidationStock:
    queue: product_validation_stock
    prefetchCount: 2
    queueType: quorum
    exchange: eca
    routingKey: eca.product_validation_stock
    deadLetterExchange: eca
    deadLetterRoutingKey: eca.product_validation_stock
    retryTime: 3000
    maxRetries: 1
  productSubtractStock:
    queue: product_subtract_stock
    prefetchCount: 1
    queueType: quorum
    exchange: eca
    routingKey: eca.product_subtract_stock
    deadLetterExchange: eca
    deadLetterRoutingKey: eca.product_subtract_stock
    retryTime: 3000
    maxRetries: 1
    numOfConsumer: 10

catalogProducer:
  orderConfirmedStock:
    exchange: eca
    routingKey: eca.order_confirmed_stock
  orderRejectedStock:
    exchange: eca
    routingKey: eca.order_rejected_stock