http:
  host: 'localhost'
  port: 4017
  contextPath: catalog

description: 'Product Service'

rabbit:
  protocol: amqp
  hostname: localhost
  username: guest
  password: guest
  port: 5672
  heartbeat: 1
  queue: 'localhost'
  retry:
    # forever: true
    retries: 5
    factor: 1
    minTimeout: 3000
    maxTimeout: 20000
mongoose:
  uri: mongodb://localhost:27017/catalog
redis:
  url: localhost
  password: null
  socket:
    port: 6379
    connectTimeout: 60000
  database: 1

throttler:
  - name: short
    ttl: 1000
    limit: 3
  - name: medium
    ttl: 10000
    limit: 20
  - name: long
    ttl: 60000
    limit: 100