apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: 'mongodb'
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          # command:
          # - mongod
          # - --auth
          # - --bind_ip
          # - 0.0.0.0
          ports:
            - containerPort: 27017
              name: mongo
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
            # - name: init-user
            #   mountPath: /docker-entrypoint-initdb.d/mongo-init.js:ro
          env:
            # - name: MONGO_INITDB_ROOT_USERNAME
            #   valueFrom:
            #     secretKeyRef:
            #       name: mongodb-auth
            #       key: username
            # - name: MONGO_INITDB_ROOT_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: mongodb-auth
            #       key: password
      # volumes:
      #   - name: init-user
      #     hostPath:
      #       path: mongo-init.js
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30002
