version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: giangnt
      POSTGRES_PASSWORD: giangnt
      POSTGRES_DB: admin
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data # Persist data across container restarts

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: giangnguyen3246@gmail.com
      PGADMIN_DEFAULT_PASSWORD: '123456'
    ports:
      - '5050:80'
    depends_on:
      - postgres # Ensure pgAdmin starts after PostgreSQL
