version: '3'

services:
  jenkins:
    container_name: 'jenkins-container'
    privileged: true
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8090:8080'
      - '50000:50000'
    volumes:
      - D:\jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped