http:
  host: 'localhost'
  port: 4050
  contextPath: api/v1

description: 'Realtime Service'

rabbit:
  protocol: amqp
  hostname: localhost
  username: guest
  password: guest
  port: 5672
  heartbeat: 1
  queue: 'localhost'
  retry:
    # forever: true
    retries: 5
    factor: 1
    minTimeout: 3000
    maxTimeout: 20000

typeOrm:
  type: mysql
  host: localhost
  username: root
  password: '123456'
  port: 3306
  synchronize: true
  autoLoadEntities: true
  database: eca_crawler
  logging: true
  
redis:
  host: localhost
  port: 6379
  password: null
  db: 1

mongoose:
  uri: mongodb://localhost:27017/microservice

throttler:
  - name: short
    ttl: 1000
    limit: 3
  - name: medium
    ttl: 10000
    limit: 20
  - name: long
    ttl: 60000
    limit: 100

authConfig:
  accessTokenKey: HAHAHAHAAHA
  refreshTokenKey: HEHEHEEHE
  accessTokenExpiresTime: 6000
  refreshTokenExpiresTime: 3600000
  identityApi: http://localhost:4016/api/v1

socketConsumer: 
  eventRealTimeListening:
    queue: event_real_time
    prefetchCount: 2
    queueType: quorum
    exchange: real_time
    routingKey: event_real_time
    deadLetterExchange: real_time
    deadLetterRoutingKey: event_real_time.errors
    retryTime: 3000
    maxRetries: 1