http:
  host: 'localhost'
  port: 4098
  contextPath: ordering

description: 'Ordering Service'

rabbit:
  protocol: amqp
  hostname: localhost
  username: guest
  password: guest
  port: 5672
  heartbeat: 1
  queue: 'localhost'
  retry:
    # forever: true
    retries: 5
    factor: 1
    minTimeout: 3000
    maxTimeout: 20000
mongoose:
  uri: mongodb://localhost:27017/microservice

redis:
  url: localhost
  password: null
  socket:
    port: 6379
    connectTimeout: 60000
  database: 1

typeOrm:
  type: postgres
  host: localhost
  username: giangnt
  password: 'giangnt'
  port: 5432
  synchronize: true
  autoLoadEntities: true
  database: ordering
  logging: false

throttler:
  - name: short
    ttl: 1000
    limit: 3
  - name: medium
    ttl: 10000
    limit: 20
  - name: long
    ttl: 60000
    limit: 100

orderingConsumer:
  orderCreated:
    queue: order_created
    prefetchCount: 2
    queueType: quorum
    exchange: eca
    routingKey: eca.order_created
    deadLetterExchange: eca
    deadLetterRoutingKey: eca.order_created
    retryTime: 3000
    maxRetries: 1
    numOfConsumer: 10
  
  orderConfirmedStock:
    queue: order_confirmed_stock
    prefetchCount: 2
    queueType: quorum
    exchange: eca
    routingKey: eca.order_confirmed_stock
    deadLetterExchange: eca
    deadLetterRoutingKey: eca.order_confirmed_stock
    retryTime: 3000
    maxRetries: 1

  orderConfirmedPayment:
    queue: order_confirmed_payment
    prefetchCount: 2
    queueType: quorum
    exchange: eca
    routingKey: eca.order_confirmed_payment
    deadLetterExchange: eca
    deadLetterRoutingKey: eca.order_confirmed_payment
    retryTime: 3000
    maxRetries: 1

  orderRejectedStock:
    queue: order_rejected_stock
    prefetchCount: 2
    queueType: quorum
    exchange: eca
    routingKey: eca.order_rejected_stock
    deadLetterExchange: eca
    deadLetterRoutingKey: eca.order_rejected_stock
    retryTime: 3000
    maxRetries: 1

orderingProducer:
  cartDeleted:
    exchange: eca
    routingKey: eca.cart_deleted
  productValidationStock:
    exchange: eca
    routingKey: eca.product_validation_stock
  paymentCheckoutOrder:
    exchange: eca
    routingKey: eca.payment_checkout_order
  productSubtractStock:
    exchange: eca
    routingKey: eca.product_subtract_stock
