export enum REPO {
  ORDER = 'ORDER_REPO',
  ORDER_ITEM = 'ORDER_ITEM_REPO',
  BUYER = 'BUYER_REPO',
  LOG_EVENT = 'LOG_EVENT_REPO',
}

export enum PRODUCER_PROCESS {
  CART_DELETED = 'CART_DELETED',
}
